// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW2tVTiAoJMPZp3utJFQg5ZFvBFFfugW4',
    appId: '1:949076644731:web:e003a1bbd9c986017563de',
    messagingSenderId: '949076644731',
    projectId: 'kawanlamamrbsworkspace',
    authDomain: 'kawanlamamrbsworkspace.firebaseapp.com',
    databaseURL: 'https://kawanlamamrbsworkspace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kawanlamamrbsworkspace.appspot.com',
    measurementId: 'G-G89HLYRFGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMImj7StW30juDLPmOqBB5TZhtyIdvp4',
    appId: '1:949076644731:android:c66a48a6082938737563de',
    messagingSenderId: '949076644731',
    projectId: 'kawanlamamrbsworkspace',
    databaseURL: 'https://kawanlamamrbsworkspace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kawanlamamrbsworkspace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4pxrxylHW1qnPsM5VhKrztbCYiyoCK4',
    appId: '1:949076644731:ios:3bcf3940e38acf7e7563de',
    messagingSenderId: '949076644731',
    projectId: 'kawanlamamrbsworkspace',
    databaseURL: 'https://kawanlamamrbsworkspace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kawanlamamrbsworkspace.appspot.com',
    iosClientId: '949076644731-idkbs5bnrs9gtpnuji2k46of143tt4h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrbsTablet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa4pxrxylHW1qnPsM5VhKrztbCYiyoCK4',
    appId: '1:949076644731:ios:3bcf3940e38acf7e7563de',
    messagingSenderId: '949076644731',
    projectId: 'kawanlamamrbsworkspace',
    databaseURL: 'https://kawanlamamrbsworkspace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kawanlamamrbsworkspace.appspot.com',
    iosClientId: '949076644731-idkbs5bnrs9gtpnuji2k46of143tt4h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrbsTablet',
  );
}
