// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRc1Z5CQE9iNOGhkbNFl8klclydjQMtY',
    appId: '1:425240684876:web:a28012a8b11e805fc787e9',
    messagingSenderId: '425240684876',
    projectId: 'mrbsproduction',
    authDomain: 'mrbsproduction.firebaseapp.com',
    databaseURL: 'https://mrbsproduction-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mrbsproduction.appspot.com',
    measurementId: 'G-ZZCHPY4PDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGbb4aDXDD5vtAEPfwr1It4n_dODYQR8',
    appId: '1:425240684876:android:4de4eda01e7feceec787e9',
    messagingSenderId: '425240684876',
    projectId: 'mrbsproduction',
    databaseURL: 'https://mrbsproduction-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mrbsproduction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaacNCmmeClQVr6zhmTWbdGEiEHcjMUh0',
    appId: '1:425240684876:ios:bdbfbba657636f61c787e9',
    messagingSenderId: '425240684876',
    projectId: 'mrbsproduction',
    databaseURL: 'https://mrbsproduction-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mrbsproduction.appspot.com',
    iosClientId: '425240684876-u3pkpcv0c3546i7hmob06tbu878al1uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrbsTablet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaacNCmmeClQVr6zhmTWbdGEiEHcjMUh0',
    appId: '1:425240684876:ios:bdbfbba657636f61c787e9',
    messagingSenderId: '425240684876',
    projectId: 'mrbsproduction',
    databaseURL: 'https://mrbsproduction-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mrbsproduction.appspot.com',
    iosClientId: '425240684876-u3pkpcv0c3546i7hmob06tbu878al1uq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrbsTablet',
  );
}
